Repository prometheus-community/windows_exporter, pull requests merged in 2023-03, with the labels that each got.

#1152 chore(deps): Update wmi to v1.2.2
  .github/workflows/lint.yml
  collector/ad.go
  collector/cpu_info.go
  collector/diskdrive.go
  collector/dns.go
  collector/fsrmquota.go
  collector/hyperv.go
  collector/logon.go
  collector/mscluster_cluster.go
  collector/mscluster_network.go
  collector/mscluster_node.go
  collector/mscluster_resource.go
  collector/mscluster_resourcegroup.go
  collector/msmq.go
  collector/netframework_clrexceptions.go
  collector/netframework_clrinterop.go
  collector/netframework_clrjit.go
  collector/netframework_clrloading.go
  collector/netframework_clrlocksandthreads.go
  collector/netframework_clrmemory.go
  collector/netframework_clrremoting.go
  collector/netframework_clrsecurity.go
  collector/process.go
  collector/service.go
  collector/teradici_pcoip.go
  collector/terminal_services.go
  collector/thermalzone.go
  collector/vmware.go
  collector/vmware_blast.go
  exporter.go
  go.mod
  go.sum
  headers/netapi32/netapi32.go
  initiate/initiate.go
  tools/collector-generator/collector.template
Labels: ci/builds, dependencies

#1148 Update collector.iis.md
  docs/collector.iis.md
Labels: collector/iis

#1144 docs: fix documentation error
  README.md
Labels: documentation

#1166 feat: Add output_queue_length metric to net collector
  collector/net.go
  docs/collector.net.md
  tools/e2e-output.txt
Labels: collector/net

#1167 chore(ci): Update release workflow actions
  .github/workflows/release.yml
Labels: ci/builds
