Repository prometheus-community/windows_exporter, pull requests merged in 2024-10, with the labels that each got.

#1637 cpu: add workaround for counter resets related to `% Processor Utility` metric
  pkg/collector/cpu/cpu.go
Labels: 🐞 bug

#1652 updates: add windows update collector
  README.md
  docs/collector.update.md
  pkg/collector/collector.go
  pkg/collector/config.go
  pkg/collector/map.go
  pkg/collector/updates/updates.go
  pkg/collector/updates/updates_test.go
Labels: ✨ enhancement

#1638 tcp: use GetExtendedTcpTable to display states Closed, Listening, SynSent, SynRcvd, CloseWait, TimeWait ...
  docs/collector.tcp.md
  pkg/collector/tcp/const.go
  pkg/collector/tcp/tcp.go
  pkg/headers/iphlpapi/const.go
  pkg/headers/iphlpapi/iphlpapi.go
  pkg/headers/iphlpapi/types.go
Labels: ✨ enhancement

#1635 net: expose network interfaces address
  pkg/collector/net/const.go
  pkg/collector/net/net.go
  pkg/collector/net/net_test.go
  pkg/collector/tcp/tcp.go
  tools/e2e-output.txt
Labels: ✨ enhancement

#1659 *: replace `--collectors.[name].*` with `--collector.[name].*` flags (click PR number for more information)
  pkg/collector/dfsr/dfsr.go
  pkg/collector/exchange/exchange.go
  pkg/collector/filetime/filetime.go
  pkg/collector/mscluster/mscluster.go
  pkg/collector/mssql/mssql.go
Labels: 💥 breaking-change

#1662 cache: Implement PDH collector
  pkg/collector/ad/ad.go
  pkg/collector/adcs/adcs.go
  pkg/collector/adfs/adfs.go
  pkg/collector/cache/cache.go
  pkg/collector/cache/const.go
  pkg/collector/prometheus.go
  pkg/perfdata/collector.go
  tools/e2e-output.txt
  tools/end-to-end-test.ps1
Labels: ✨ enhancement

#1663 dfsr: Implement PDH collector
  pkg/collector/cpu_info/cpu_info.go
  pkg/collector/dfsr/const.go
  pkg/collector/dfsr/dfsr.go
Labels: ✨ enhancement

#1665 chore: cleanup move private packages to internal
  installer/files.wxs
  internal/collector/ad/ad.go
  internal/collector/adcs/adcs.go
  internal/collector/adcs/adcs_test.go
  internal/collector/adfs/adfs.go
  internal/collector/cache/cache.go
  internal/collector/container/container.go
  internal/collector/cpu/cpu.go
  internal/collector/cpu_info/cpu_info.go
  internal/collector/cs/cs.go
  internal/collector/dfsr/dfsr.go
  internal/collector/dhcp/dhcp.go
  internal/collector/diskdrive/diskdrive.go
  internal/collector/dns/dns.go
  internal/collector/exchange/exchange.go
  internal/collector/filetime/filetime.go
  internal/collector/fsrmquota/fsrmquota.go
  internal/collector/hyperv/hyperv.go
  internal/collector/iis/iis.go
  internal/collector/license/license.go
  internal/collector/logical_disk/logical_disk.go
  internal/collector/logon/logon.go
  internal/collector/memory/memory.go
  internal/collector/msmq/msmq.go
  internal/collector/mssql/mssql.go
  internal/collector/net/net.go
  internal/collector/nps/nps.go
  internal/collector/os/os.go
  internal/collector/perfdata/perfdata.go
  internal/collector/perfdata/perfdata_collector_test.go
  internal/collector/physical_disk/physical_disk.go
  internal/collector/printer/printer.go
  internal/collector/process/process.go
  internal/collector/remote_fx/remote_fx.go
  internal/collector/scheduled_task/scheduled_task.go
  internal/collector/service/service.go
  internal/collector/smb/smb.go
  internal/collector/smbclient/smbclient.go
  internal/collector/smtp/smtp.go
  internal/collector/system/system.go
  internal/collector/tcp/tcp.go
  internal/collector/teradici_pcoip/teradici_pcoip.go
  internal/collector/terminal_services/terminal_services.go
  internal/collector/textfile/textfile.go
  internal/collector/thermalzone/thermalzone.go
  internal/collector/time/time.go
  internal/collector/updates/updates.go
  internal/collector/vmware/vmware.go
  internal/collector/vmware_blast/vmware_blast.go
  pkg/collector/prometheus.go
Labels: chore

#1666 process: Implement PDH collector and add support for Process V2
  internal/collector/adcs/adcs.go
  internal/collector/process/const.go
  internal/collector/process/process.go
Labels: ✨ enhancement

#1670 *: Implement collector interface for registry perfdata
  .github/workflows/release.yml
  .golangci.yaml
  internal/collector/ad/ad.go
  internal/collector/adcs/adcs.go
  internal/collector/adfs/adfs.go
  internal/collector/cache/cache.go
  internal/collector/container/container.go
  internal/collector/cpu/cpu.go
  internal/collector/dfsr/dfsr.go
  internal/collector/dhcp/dhcp.go
  internal/collector/exchange/exchange.go
  internal/collector/iis/iis.go
  internal/collector/logical_disk/logical_disk.go
  internal/collector/memory/memory.go
  internal/collector/mssql/mssql.go
  internal/collector/net/net.go
  internal/collector/os/os.go
  internal/collector/perfdata/perfdata.go
  internal/collector/perfdata/types.go
  internal/collector/physical_disk/physical_disk.go
  internal/collector/process/process.go
  internal/collector/remote_fx/remote_fx.go
  internal/collector/smb/smb.go
  internal/collector/smbclient/smbclient.go
  internal/collector/smtp/smtp.go
  internal/collector/system/system.go
  internal/collector/tcp/tcp.go
  internal/collector/terminal_services/terminal_services.go
  internal/collector/time/time.go
  internal/collector/vmware/vmware.go
  internal/perfdata/perfdata.go
  internal/perfdata/perftypes/const.go
  internal/perfdata/perftypes/types.go
  internal/perfdata/v1/LICENSE
  internal/perfdata/v1/collector.go
  internal/perfdata/v1/nametable.go
  internal/perfdata/v1/perflib.go
  internal/perfdata/v1/perflib_test.go
  internal/perfdata/v1/raw_types.go
  internal/perfdata/v1/unmarshal.go
  internal/perfdata/v1/utf16.go
  internal/perfdata/v1/utils.go
  internal/perfdata/v1/utils_test.go
  internal/perfdata/v2/collector.go
  internal/perfdata/v2/collector_bench_test.go
  internal/perfdata/v2/collector_test.go
  internal/perfdata/v2/error.go
  internal/perfdata/v2/pdh.go
  internal/perfdata/v2/pdh_amd64.go
  internal/perfdata/v2/pdh_arm64.go
  internal/perflib/const.go
  internal/types/types.go
  pkg/collector/collector.go
Labels: chore

#1671 dhcp: Use new collector interface
  internal/collector/dfsr/dfsr.go
  internal/collector/dhcp/const.go
  internal/collector/dhcp/dhcp.go
Labels: chore

#1672 dns: Implement Perfdata collector
  internal/collector/dns/const.go
  internal/collector/dns/dns.go
Labels: chore

#1673 logical_disk: Implement Perfdata collector
  .golangci.yaml
  internal/collector/cpu/cpu_test.go
  internal/collector/cpu_info/cpu_info_test.go
  internal/collector/dhcp/dhcp.go
  internal/collector/filetime/filetime.go
  internal/collector/filetime/filetime_test.go
  internal/collector/license/license_test.go
  internal/collector/logical_disk/const.go
  internal/collector/logical_disk/logical_disk.go
  internal/collector/logical_disk/logical_disk_test.go
  internal/collector/logon/logon_test.go
  internal/collector/net/net_test.go
  internal/collector/os/os_test.go
  internal/collector/physical_disk/physical_disk_test.go
  internal/collector/printer/printer_test.go
  internal/collector/process/process_test.go
  internal/perfdata/v1/collector.go
  internal/perfdata/v1/perflib.go
  internal/testutils/testutils.go
Labels: chore

#1679 *: [0.27] don't exclude resources, if exclude option is empty.
  pkg/types/regexp.go
Labels: 🐞 bug

#1682 chore(docs): fix link to update collector
  README.md
Labels: 📖 docs

#1680 *: don't exclude resources, if empty exclude is empty.
  internal/collector/iis/iis.go
  internal/collector/logical_disk/logical_disk.go
  internal/collector/net/net.go
  internal/collector/physical_disk/physical_disk.go
  internal/collector/printer/printer.go
  internal/collector/process/process.go
  internal/collector/scheduled_task/scheduled_task.go
  internal/collector/service/service.go
  internal/collector/smtp/smtp.go
  internal/types/regexp.go
Labels: 🐞 bug

#1676 memory: Implement perfdata collector
  internal/collector/memory/const.go
  internal/collector/memory/memory.go
  internal/collector/memory/memory_test.go
Labels: chore

#1683 chore: optimize registry collector
  internal/perfdata/v1/collector.go
  internal/perfdata/v1/perflib.go
  internal/perfdata/v1/perflib_test.go
  internal/perfdata/v1/utils.go
Labels: chore

#1685 exchange: Use new collector interface
  .golangci.yaml
  internal/collector/exchange/exchange.go
  internal/collector/exchange/exchange_active_sync.go
  internal/collector/exchange/exchange_ad_access_processes.go
  internal/collector/exchange/exchange_autodiscover.go
  internal/collector/exchange/exchange_availability_service.go
  internal/collector/exchange/exchange_http_proxy.go
  internal/collector/exchange/exchange_mapi_http_emsmdb.go
  internal/collector/exchange/exchange_outlook_web_access.go
  internal/collector/exchange/exchange_rpc_client_access.go
  internal/collector/exchange/exchange_transport_queues.go
  internal/collector/exchange/exchange_workload_management.go
Labels: ✨ enhancement

#1686 *: Remove `teradici_pcoip` and `vmware_blast` collector
  README.md
  docs/README.md
  docs/collector.teradici_pcoip.md
  docs/collector.vmware_blast.md
  internal/collector/teradici_pcoip/teradici_pcoip.go
  internal/collector/teradici_pcoip/teradici_pcoip_test.go
  internal/collector/vmware_blast/vmware_blast.go
  internal/collector/vmware_blast/vmware_blast_test.go
  pkg/collector/collector.go
  pkg/collector/config.go
  pkg/collector/map.go
Labels: 💥 breaking-change

#1687 logon: BREAKING: replace wmi query by Win32 API calls and expose detailed logon sessions. (click PR for more information)
  README.md
  docs/collector.logon.md
  internal/collector/logon/logon.go
  internal/headers/secur32/secur32.go
  internal/headers/secur32/secur32_test.go
  internal/headers/secur32/types.go
Labels: ✨ enhancement, 💥 breaking-change

#1690 docs: add actual Windows Update service name
  docs/collector.update.md
Labels: 📖 docs

#1693 fix: fail, if unknown collector is defined in enabled list
  exporter.go
  pkg/collector/collector.go
Labels: 🐞 bug

#1699 tcp: fix panic on collector
  internal/collector/tcp/tcp_test.go
  internal/perfdata/v1/collector.go
  internal/perfdata/v1/perflib.go
Labels: 🐞 bug

#1702 docs: Add log.file argument to README
  README.md
Labels: 📖 docs
