Repository prometheus-community/windows_exporter, pull requests merged in 2024-11, with the labels that each got.

#1715 cpu: implement int32 counter for PDH calls as well.
  internal/collector/cpu/cpu.go
  internal/perfdata/perfdata.go
  internal/utils/counter.go
  internal/utils/counter_test.go
Labels: chore

#1722 docs: Update textfile collector defaults inclusion
  docs/collector.textfile.md
Labels: 📖 docs

#1723 feat: add perfcounter.engine CLI option as alternative to WINDOWS_EXPORTER_PERF_COUNTERS_ENGINE env
  .github/workflows/pr-check.yaml
  exporter.go
  internal/collector/adcs/adcs.go
  internal/collector/adfs/adfs.go
  internal/collector/cache/cache.go
  internal/collector/cpu/cpu.go
  internal/collector/dfsr/dfsr.go
  internal/collector/dhcp/dhcp.go
  internal/collector/exchange/exchange.go
  internal/collector/logical_disk/logical_disk.go
  internal/collector/memory/memory.go
  internal/collector/net/net.go
  internal/collector/process/process.go
  internal/testutils/testutils.go
  internal/toggle/main.go
  internal/utils/collector.go
Labels: ✨ enhancement

#1727 vmware: refactor collector
  docs/collector.vmware.md
  internal/collector/vmware/const.go
  internal/collector/vmware/vmware.go
  internal/perfdata/perftypes/types.go
  internal/perfdata/v2/collector.go
  internal/utils/utils.go
Labels: ✨ enhancement

#1728 time: refactor collector
  docs/collector.time.md
  internal/collector/service/service_test.go
  internal/collector/time/const.go
  internal/collector/time/time.go
  internal/collector/time/time_test.go
  internal/collector/vmware/const.go
  internal/collector/vmware/vmware.go
Labels: ✨ enhancement

#1729 terminal_services: refactor collector
  internal/collector/terminal_services/const.go
  internal/collector/terminal_services/terminal_services.go
  internal/headers/wtsapi32/wtsapi32.go
  internal/mi/callbacks.go
  internal/mi/session.go
Labels: ✨ enhancement

#1730 system: refactor collector
  exporter.go
  internal/collector/cpu/cpu.go
  internal/collector/system/const.go
  internal/collector/system/system.go
  internal/collector/terminal_services/const.go
  internal/collector/terminal_services/terminal_services.go
  internal/perfdata/perftypes/const.go
  internal/perfdata/v2/collector.go
  internal/perfdata/v2/pdh.go
Labels: ✨ enhancement

#1731 chore: Switch to hostprocess base image and add support for Windows Server 2025 on Kubernetes (click PR number for more information)
  .github/workflows/release.yml
  Dockerfile
  Dockerfile.cross
  Makefile
Labels: ✨ enhancement, 💥 breaking-change

#1735 pagefile: BREAKING: move paging metrics from os to dedicated collector (click PR for more information)
  README.md
  docs/collector.os.md
  docs/collector.pagefile.md
  internal/collector/os/os.go
  internal/collector/pagefile/const.go
  internal/collector/pagefile/pagefile.go
  internal/collector/pagefile/pagefile_test.go
  internal/perfdata/v2/collector.go
  pkg/collector/collector.go
  pkg/collector/config.go
  pkg/collector/map.go
  tools/e2e-output.txt
  tools/end-to-end-test.ps1
Labels: ✨ enhancement, 💥 breaking-change

#1737 chore: use slog instead gokit for logging style
  internal/log/logger.go
Labels: chore

#1738 remote_fx: refactor collector
  internal/collector/ad/ad.go
  internal/collector/adcs/adcs.go
  internal/collector/adfs/adfs.go
  internal/collector/cache/cache.go
  internal/collector/cpu/cpu.go
  internal/collector/dfsr/dfsr.go
  internal/collector/dhcp/dhcp.go
  internal/collector/dns/dns.go
  internal/collector/exchange/exchange_active_sync.go
  internal/collector/exchange/exchange_ad_access_processes.go
  internal/collector/exchange/exchange_autodiscover.go
  internal/collector/exchange/exchange_availability_service.go
  internal/collector/exchange/exchange_http_proxy.go
  internal/collector/exchange/exchange_mapi_http_emsmdb.go
  internal/collector/exchange/exchange_outlook_web_access.go
  internal/collector/exchange/exchange_rpc_client_access.go
  internal/collector/exchange/exchange_transport_queues.go
  internal/collector/exchange/exchange_workload_management.go
  internal/collector/logical_disk/logical_disk.go
  internal/collector/memory/memory.go
  internal/collector/net/net.go
  internal/collector/pagefile/pagefile.go
  internal/collector/process/process.go
  internal/collector/remote_fx/const.go
  internal/collector/remote_fx/remote_fx.go
  internal/collector/service/service.go
  internal/collector/system/const.go
  internal/collector/system/system.go
  internal/collector/thermalzone/thermalzone.go
  internal/collector/time/time.go
  internal/collector/update/update.go
  internal/collector/vmware/vmware.go
Labels: ✨ enhancement

#1739 smtp: refactor collector
  internal/collector/smtp/const.go
  internal/collector/smtp/smtp.go
Labels: ✨ enhancement

#1740 smb: refactor collector
  internal/collector/smb/const.go
  internal/collector/smb/smb.go
  internal/collector/smbclient/const.go
  internal/collector/smbclient/smbclient.go
Labels: ✨ enhancement

#1744 service: parallelize api calls
  internal/collector/cpu/cpu.go
  internal/collector/service/service.go
Labels: ✨ enhancement

#1745 service: fixed buffer too low error
  internal/collector/service/service.go
Labels: 🐞 bug

#1747 logicaldisk: fix base counter values
  internal/collector/logical_disk/logical_disk.go
  internal/collector/mssql/mssql_access_methods.go
  internal/collector/mssql/mssql_buffer_manager.go
  internal/collector/mssql/mssql_database.go
  internal/collector/mssql/mssql_locks.go
  internal/perfdata/collector.go
Labels: 🐞 bug

#1741 mssql: expose server version info
  docs/collector.mssql.md
  go.mod
  internal/collector/mssql/mssql.go
  internal/headers/iphlpapi/const.go
  internal/headers/iphlpapi/iphlpapi.go
  internal/headers/iphlpapi/iphlpapi_test.go
  internal/headers/iphlpapi/types.go
Labels: ✨ enhancement

#1712 hyperv: Refactor collector, added DataStore, Virtual SMB and Dynamic Memory Balancer metrics (click PR number for more information)
  .github/workflows/spelling.yml
  docs/collector.hyperv.md
  internal/collector/cpu/cpu.go
  internal/collector/cs/cs.go
  internal/collector/hyperv/hyperv.go
  internal/collector/hyperv/hyperv_datastore.go
  internal/collector/hyperv/hyperv_dynamic_memory_balancer.go
  internal/collector/hyperv/hyperv_dynamic_memory_vm.go
  internal/collector/hyperv/hyperv_hypervisor_logical_processor.go
  internal/collector/hyperv/hyperv_hypervisor_root_partition.go
  internal/collector/hyperv/hyperv_hypervisor_root_virtual_processor.go
  internal/collector/hyperv/hyperv_hypervisor_virtual_processor.go
  internal/collector/hyperv/hyperv_legacy_network_adapter.go
  internal/collector/hyperv/hyperv_virtual_machine_health_summary.go
  internal/collector/hyperv/hyperv_virtual_machine_vid_partition.go
  internal/collector/hyperv/hyperv_virtual_network_adapter.go
  internal/collector/hyperv/hyperv_virtual_network_adapter_drop_reasons.go
  internal/collector/hyperv/hyperv_virtual_smb.go
  internal/collector/hyperv/hyperv_virtual_storage_device.go
  internal/collector/hyperv/hyperv_virtual_switch.go
  internal/collector/mscluster/mscluster.go
  internal/collector/mscluster/mscluster_cluster.go
  internal/collector/mscluster/mscluster_network.go
  internal/collector/mscluster/mscluster_node.go
  internal/collector/mscluster/mscluster_resource.go
  internal/collector/mscluster/mscluster_resourcegroup.go
  internal/perfdata/collector.go
  internal/perfdata/error.go
  internal/utils/utils.go
Labels: ✨ enhancement, 💥 breaking-change

#1749 exchange: Extend Transport Queue metrics
  docs/collector.exchange.md
  internal/collector/exchange/exchange.go
  internal/collector/exchange/exchange_active_sync.go
  internal/collector/exchange/exchange_ad_access_processes.go
  internal/collector/exchange/exchange_autodiscover.go
  internal/collector/exchange/exchange_availability_service.go
  internal/collector/exchange/exchange_http_proxy.go
  internal/collector/exchange/exchange_mapi_http_emsmdb.go
  internal/collector/exchange/exchange_outlook_web_access.go
  internal/collector/exchange/exchange_rpc_client_access.go
  internal/collector/exchange/exchange_transport_queues.go
  internal/collector/exchange/exchange_workload_management.go
Labels: ✨ enhancement

#1752 logical_disk: Get Volume ID for NTFS Volume Mounts
  internal/collector/logical_disk/logical_disk.go
Labels: 🐞 bug

#1755 logical_disk: revert panic trigger on error
  internal/collector/logical_disk/logical_disk.go
Labels: 🐞 bug

#1760 collector: remove windows_exporter_perflib_snapshot_duration_seconds metric
  internal/collector/memory/memory.go
  internal/collector/mscluster/mscluster.go
  internal/collector/smtp/smtp.go
  pkg/collector/prometheus.go
  tools/e2e-output.txt
  tools/end-to-end-test.ps1
Labels: 🐞 bug

#1761 adfs: fix collector
  internal/collector/adfs/adfs.go
  internal/collector/adfs/const.go
  internal/collector/dhcp/dhcp.go
Labels: 🐞 bug

#1763 collector: fix wrong perfdata instances
  internal/collector/adfs/adfs.go
  internal/collector/nps/nps.go
  internal/collector/remote_fx/const.go
  internal/collector/smb/smb.go
  internal/collector/smbclient/smbclient.go
  internal/collector/update/update.go
Labels: 🐞 bug

#1764 nps: refactor collector
  internal/collector/nps/const.go
  internal/collector/nps/nps.go
Labels: ✨ enhancement

#1766 msmq: Use Performance Counter instead WMI
  docs/collector.msmq.md
  internal/collector/msmq/const.go
  internal/collector/msmq/msmq.go
  internal/collector/smb/smb.go
Labels: ✨ enhancement

#1759 mscluster: fix cluster and network sub collectors
  internal/collector/mscluster/mscluster.go
  internal/collector/mscluster/mscluster_cluster.go
  internal/collector/mscluster/mscluster_network.go
  internal/collector/mscluster/mscluster_node.go
  internal/collector/mscluster/mscluster_resource.go
  internal/collector/mscluster/mscluster_resourcegroup.go
Labels: 🐞 bug

#1768 chore: move exporter binary to cmd package
  .golangci.yaml
  .promu.yml
  cmd/windows_exporter/doc.go
  cmd/windows_exporter/main.go
  cmd/windows_exporter/winres/icon.png
  cmd/windows_exporter/winres/winres.json
  internal/log/eventlog/eventlog.go
  internal/windowsservice/doc.go
  internal/windowsservice/init.go
  internal/windowsservice/log.go
  internal/windowsservice/windowsservice.go
  winres/winres.json
Labels: chore

#1773 collector: refactor metrics handler
  internal/httphandler/httphandler.go
  pkg/collector/collect.go
  pkg/collector/collection.go
  pkg/collector/handler.go
  pkg/collector/types.go
Labels: chore

#1771 fix: use log.file=eventlog as default value, if running as windows service
  cmd/windows_exporter/main.go
  installer/files.wxs
  installer/main.wxs
  internal/log/flag/flag.go
  internal/log/logger.go
Labels: 🐞 bug

#1775 textfile: set windows_exporter_collector_success to 0, if an errors occurs
  internal/collector/net/net.go
  internal/collector/textfile/textfile.go
  internal/collector/textfile/textfile_test_test.go
Labels: 🐞 bug

#1776 collector: don't fail if perf counters are empty.
  pkg/collector/collect.go
Labels: 🐞 bug

#1777 mssql: set windows_exporter_collector_success to 0, if errors occurs
  internal/collector/mssql/mssql.go
Labels: 🐞 bug

#1784 system: BREAKING rename `windows_system_system_up_time` to `windows_system_boot_time_timestamp_seconds`
  docs/collector.system.md
  internal/collector/system/system.go
  tools/e2e-output.txt
Labels: 💥 breaking-change

#1785 hyperv: Removed `% Guest Idle Time` performance counters (introduced in 0.30.0-beta.4)
  internal/collector/hyperv/hyperv_hypervisor_root_virtual_processor.go
  internal/collector/hyperv/hyperv_hypervisor_virtual_processor.go
Labels: 🐞 bug

#1786 logical_disk: fix volume access with limited permission
  internal/collector/logical_disk/logical_disk.go
Labels: 🐞 bug

#1787 performancecounter: rename collector
  README.md
  docs/README.md
  docs/collector.perfdata.md
  docs/collector.performancecounter.md
  internal/collector/performancecounter/performancecounter.go
  internal/collector/performancecounter/performancecounter_test.go
  internal/collector/performancecounter/performancecounter_test_test.go
  internal/collector/performancecounter/types.go
  pkg/collector/collection.go
  pkg/collector/config.go
  pkg/collector/map.go
  tools/e2e-output.txt
  tools/end-to-end-test.ps1
Labels: ✨ enhancement

#1791 vmware: fix memory collector
  internal/collector/vmware/const.go
Labels: 🐞 bug

#1792 iis: Fix label for Default Web Site
  .run/all.run.xml
  internal/collector/iis/iis_app_pool_was.go
  internal/collector/iis/iis_web_service_cache.go
Labels: 🐞 bug

#1793 mssql: fix not collecting sql errors
  internal/collector/mssql/mssql_sql_errors.go
  internal/collector/mssql/mssql_sql_stats.go
Labels: 🐞 bug

#1796 chore: update deps
  go.mod
  go.sum
Labels: chore
