Repository prometheus-community/windows_exporter, pull requests merged in 2025-01, with the labels that each got.

#1834 docs: add CONTRIBUTING.md docs
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: 📖 docs

#1833 netframework: add --collector.netframework.enabled CLI flag
  internal/collector/netframework/netframework.go
Labels: 🐞 bug

#1839 net: fix sanitize # on the nic label for windows_net_nic_address_info
  internal/collector/net/net.go
Labels: 🐞 bug

#1841 fix: Windows 11/Windows Server 2025 service compatibility
  cmd/windows_exporter/0_service.go
  cmd/windows_exporter/main.go
  installer/files.wxs
  internal/log/eventlog/eventlog.go
  internal/windowsservice/doc.go
  internal/windowsservice/init.go
  internal/windowsservice/log.go
  internal/windowsservice/windowsservice.go
Labels: 🐞 bug

#1840 dhcp: add dhcp scope stats
  docs/collector.dhcp.md
  docs/collector.net.md
  docs/collector.netframework.md
  internal/collector/dhcp/dhcp.go
  internal/headers/dhcpsapi/dhcpsapi.go
  internal/headers/dhcpsapi/dhcpsapi_test.go
  internal/headers/dhcpsapi/types.go
  internal/headers/win32api/types.go
Labels: ✨ enhancement

#1844 docs: fix typo in README.md
  README.md
Labels: 📖 docs

#1849 config: deprecate remote http configuration
  installer/main.wxs
  internal/config/config.go
Labels: 💥 breaking-change

#1852 fix: process priority setting
  cmd/windows_exporter/main.go
Labels: 🐞 bug

#1853 service: re-use buffer for return all services
  internal/collector/service/service.go
Labels: chore

#1854 installer: force close application on uninstall
  installer/main.wxs
Labels: 🐞 bug

#1857 process: negative values with windows_process_start_time
  internal/collector/process/process.go
  internal/collector/process/process_v1.go
  internal/collector/process/process_v2.go
  internal/pdh/collector.go
Labels: 🐞 bug
