Repository prometheus-community/windows_exporter, pull requests merged in 2025-07, with the labels that each got.

#2104 os: missing deprecated metric windows_os_processes
  internal/collector/os/os.go
  tools/e2e-output.txt
Labels: 🐞 bug

#2098 fix: add missing concurrency lock
  internal/collector/service/service.go
  internal/httphandler/httphandler.go
  pkg/collector/handler.go
Labels: 🐞 bug

#2109 mssql: fix incorrect patch version in windows_mssql_instance_info
  internal/collector/mssql/types.go
Labels: 🐞 bug

#2096 mssql: fix ratio based counter
  internal/collector/mssql/mssql_access_methods.go
  internal/collector/mssql/mssql_buffer_manager.go
  internal/collector/mssql/mssql_database.go
  internal/collector/mssql/mssql_locks.go
Labels: 🐞 bug

#2112 system: remove windows_system_boot_time_timestamp_seconds
  internal/collector/process/process.go
  internal/collector/process/process_worker.go
  internal/collector/system/system.go
  tools/e2e-output.txt
Labels: 💥 breaking-change

#2121 Update README.md
  README.md
Labels: chore

#2130 gpu: fix windows_gpu_info metric
  .idea/dictionaries/project.xml
  docs/collector.gpu.md
  internal/collector/gpu/gpu.go
  internal/collector/gpu/utils.go
  internal/headers/gdi32/gdi32.go
  internal/headers/gdi32/gdi32_test.go
  internal/headers/gdi32/syscall.go
  internal/headers/gdi32/types.go
  internal/headers/ntdll/ntdll.go
  internal/headers/setupapi/gpu.go
  internal/headers/setupapi/types.go
  internal/headers/win32/types.go
Labels: 🐞 bug

#2132 filetime: support case insensitive matching
  go.mod
  go.sum
  internal/collector/filetime/filetime.go
Labels: ✨ enhancement

#2137 process: fix `windows_process_start_time_seconds_timestamp` return relative time on Windows Server 2019
  internal/collector/process/process_worker.go
Labels: 🐞 bug

#2142 docs: allow backport PR title prefix.
  .github/workflows/pr-check.yaml
Labels: chore

#2143 [0.30] docs: allow backport PR title prefix. (#2142)
  .github/workflows/lint.yml
  .github/workflows/pr-check.yaml
Labels: 📖 docs

#2145 diskdrive: fix not exposing state "Pred Fail" (#2101)
  internal/collector/diskdrive/diskdrive.go
Labels: 🐞 bug

#2138 [0.30] mssql: fix ratio based counter
  internal/collector/mssql/mssql_access_methods.go
  internal/collector/mssql/mssql_buffer_manager.go
  internal/collector/mssql/mssql_database.go
  internal/collector/mssql/mssql_locks.go
Labels: 🐞 bug

#2144 [0.30] os: missing deprecated metric windows_os_processes (#2104)
  internal/collector/os/os.go
  tools/e2e-output.txt
Labels: 🐞 bug

#2139 [0.30] mssql: fix incorrect patch version in windows_mssql_instance_info
  internal/collector/mssql/types.go
Labels: 🐞 bug

#2146 filetime: support windows paths (#2118)
  go.mod
  go.sum
  internal/collector/filetime/filetime.go
Labels: 🐞 bug

#2155 docs: add note about property preferences
  README.md
Labels: 📖 docs
