Repository prometheus-community/windows_exporter, pull requests merged in 2025-04, with the labels that each got.

#1957 logon: deprecate collector. Use `terminal_services` instead
  README.md
  docs/collector.logon.md
  internal/collector/logon/logon.go
  internal/collector/os/os.go
  internal/collector/terminal_services/terminal_services.go
  tools/e2e-output.txt
Labels: 🐞 bug

#1968 chore: Update renovate.json
  renovate.json
Labels: chore

#1960 memory: fix panics if metrics does not exists
  cmd/windows_exporter/main.go
  cmd/windows_exporter/main_test.go
  internal/collector/ad/ad.go
  internal/collector/adcs/adcs.go
  internal/collector/adfs/adfs.go
  internal/collector/cache/cache.go
  internal/collector/cpu/cpu.go
  internal/collector/cpu_info/cpu_info.go
  internal/collector/dfsr/dfsr.go
  internal/collector/dhcp/dhcp.go
  internal/collector/diskdrive/diskdrive.go
  internal/collector/dns/dns.go
  internal/collector/iis/iis.go
  internal/collector/logical_disk/logical_disk.go
  internal/collector/memory/memory.go
  internal/collector/mscluster/mscluster.go
  internal/collector/msmq/msmq.go
  internal/collector/net/net.go
  internal/collector/nps/nps.go
  internal/collector/os/os.go
  internal/collector/pagefile/pagefile.go
  internal/collector/physical_disk/physical_disk.go
  internal/collector/printer/printer.go
  internal/collector/remote_fx/remote_fx.go
  internal/collector/smb/smb.go
  internal/collector/smbclient/smbclient.go
  internal/collector/smtp/smtp.go
  internal/collector/system/system.go
  internal/collector/tcp/tcp.go
  internal/collector/terminal_services/terminal_services.go
  internal/collector/textfile/textfile_test_test.go
  internal/collector/thermalzone/thermalzone.go
  internal/collector/time/time.go
  internal/collector/udp/udp.go
  internal/collector/vmware/vmware.go
  internal/types/errors.go
  internal/utils/testutils/testutils.go
  pkg/collector/collection.go
  renovate.json
Labels: 🐞 bug

#1979 docs: update for #1964
  docs/collector.mssql.md
  docs/collector.net.md
Labels: 📖 docs

#1966 fix: windows_cpu_processor_utility_total is always 0
  .github/workflows/pr-check.yaml
  internal/pdh/collector.go
  internal/utils/counter.go
  internal/utils/counter_test.go
Labels: 🐞 bug

#1967 system: Metric `windows_system_boot_time_timestamp` returns a UNIX timestamp again.
  docs/collector.system.md
  internal/collector/system/system.go
  internal/collector/system/types.go
  internal/headers/kernel32/kernel32.go
  tools/e2e-output.txt
Labels: 🐞 bug

#1985 docs: Fix incorrect metric prefix in update collector documentation
  docs/collector.update.md
Labels: 📖 docs

#1986 update: fix naming flags (renamed `--collector.updates.*` to `--collector.update.*`) (click PR number for more information)
  internal/collector/update/update.go
Labels: 💥 breaking-change

#1997 docs: remove config.file.insecure-skip-verify
  README.md
Labels: 📖 docs

#1994 exchange: fix The specified counter could not be found
  docs/collector.exchange.md
  internal/collector/exchange/exchange_autodiscover.go
  internal/collector/exchange/exchange_availability_service.go
  internal/collector/exchange/exchange_transport_queues.go
Labels: 🐞 bug

#1999 dns: add enhanced metrics
  docs/collector.dns.md
  internal/collector/dns/dns.go
  internal/collector/dns/types.go
  internal/mi/types.go
Labels: ✨ enhancement

#2007 service: fix inconsistent values for windows_service_start_mode
  cmd/windows_exporter/0_service.go
  internal/collector/service/service.go
Labels: 🐞 bug

#2009 fix: Support running as Windows Service within containers [0.30.x]
  cmd/windows_exporter/0_service.go
  internal/collector/service/service.go
Labels: 🐞 bug

#2011 feat: Add config file validation
  .golangci.yaml
  internal/collector/dfsr/dfsr.go
  internal/collector/dhcp/dhcp.go
  internal/collector/dns/dns.go
  internal/collector/exchange/exchange.go
  internal/collector/filetime/filetime.go
  internal/collector/hyperv/hyperv.go
  internal/collector/iis/iis.go
  internal/collector/logical_disk/logical_disk.go
  internal/collector/mscluster/mscluster.go
  internal/collector/mssql/mssql.go
  internal/collector/net/net.go
  internal/collector/netframework/netframework.go
  internal/collector/performancecounter/types.go
  internal/collector/physical_disk/physical_disk.go
  internal/collector/printer/printer.go
  internal/collector/process/process.go
  internal/collector/scheduled_task/scheduled_task.go
  internal/collector/service/service.go
  internal/collector/smtp/smtp.go
  internal/collector/tcp/tcp.go
  internal/collector/textfile/textfile.go
  internal/collector/time/time.go
  internal/config/config.go
  pkg/collector/config.go
Labels: ✨ enhancement
