Repository prometheus-community/windows_exporter, pull requests merged in 2025-05, with the labels that each got.

#2029 docs: add example about add cmdline to process metrics.
  docs/collector.process.md
Labels: 📖 docs

#2026 terminal_services: Expose disconnected sessions agains
  internal/collector/terminal_services/terminal_services.go
Labels: 🐞 bug

#2030 docs: Remove CLI flag `telemetry.max-requests` and hardcoded to 1.
  README.md
  cmd/windows_exporter/doc.go
Labels: 💥 breaking-change

#2038 exchange: fix The specified counter could not be found (#1994)
  docs/collector.exchange.md
  internal/collector/exchange/exchange_autodiscover.go
  internal/collector/exchange/exchange_availability_service.go
  internal/collector/exchange/exchange_transport_queues.go
Labels: 🐞 bug

#2039 terminal_services: Expose disconnected sessions agains (#2026)
  internal/collector/terminal_services/terminal_services.go
Labels: 🐞 bug

#2040 dns: add enhanced metrics (#1999)
  docs/collector.dns.md
  internal/collector/dns/dns.go
  internal/collector/dns/types.go
  internal/mi/types.go
Labels: ✨ enhancement

#2042 docs: Fix typo
  docs/collector.msmq.md
Labels: 📖 docs

#1911 container: support hostprocess containers and expose kubernetes labels
  .gitignore
  .golangci.yaml
  .idea/copyright/profiles_settings.xml
  .idea/copyright/windows_exporter.xml
  .idea/dictionaries/project.xml
  .idea/go.imports.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/vcs.xml
  docs/collector.container.md
  go.mod
  go.sum
  internal/collector/container/container.go
  internal/collector/hyperv/hyperv.go
  internal/collector/hyperv/hyperv_dynamic_memory_balancer.go
  internal/collector/hyperv/hyperv_dynamic_memory_vm.go
  internal/collector/mscluster/mscluster_cluster.go
  internal/collector/mscluster/mscluster_node.go
  internal/collector/os/os.go
  internal/collector/performancecounter/performancecounter_test_test.go
  internal/collector/performancecounter/types.go
  internal/collector/textfile/textfile_test_test.go
  internal/collector/time/time.go
  internal/headers/guid/guid.go
  internal/headers/hcn/hcn.go
  internal/headers/hcn/hcn_test.go
  internal/headers/hcn/syscall.go
  internal/headers/hcn/types.go
  internal/headers/hcs/hcs.go
  internal/headers/hcs/hcs_test.go
  internal/headers/hcs/syscall.go
  internal/headers/hcs/types.go
  internal/headers/iphlpapi/iphlpapi.go
  internal/headers/iphlpapi/types.go
  internal/headers/kernel32/job.go
  internal/headers/kernel32/kernel32.go
  internal/headers/kernel32/types.go
  internal/osversion/osversion_windows.go
  internal/osversion/osversion_windows_test.go
  internal/osversion/windowsbuilds.go
  internal/pdh/collector.go
  internal/pdh/collector_test.go
  internal/pdh/registry/nametable.go
  renovate.json
Labels: ✨ enhancement, Stale

#2041 tcp: relax metrics collectos on error
  internal/collector/tcp/tcp.go
  internal/collector/udp/udp.go
  internal/headers/iphlpapi/iphlpapi.go
Labels: 🐞 bug

#2053 update: export properties so that they can be read from yaml file
  internal/collector/update/update.go
Labels: ✨ enhancement

#2054 update: export properties so that they can be read from yaml file
  internal/collector/update/update.go
Labels: 🐞 bug

#2051 service: report invalid parameter errors as debug
  internal/collector/service/service.go
Labels: 🐞 bug

#2055 chore: fix test
  cmd/windows_exporter/main_test.go
Labels: chore

#2057 container: fix collector
  .idea/dictionaries/project.xml
  internal/collector/container/container.go
  internal/headers/kernel32/job.go
  internal/headers/kernel32/types.go
Labels: chore

#2058 time: expose clock source sync
  docs/collector.time.md
  internal/collector/time/time.go
  pkg/collector/collect.go
  tools/e2e-output.txt
  tools/end-to-end-test.ps1
Labels: ✨ enhancement

#2064 process: add `collector.process.counter-version` CLI parameter
  .idea/go.imports.xml
  docs/collector.process.md
  internal/collector/process/process.go
  internal/collector/process/process_v2.go
  internal/collector/process/process_worker.go
  internal/collector/process/types.go
  internal/pdh/registry/collector.go
Labels: ✨ enhancement
