Repository prometheus-community/windows_exporter, pull requests merged in 2025-08, with the labels that each got.

#2162 installer: disable config file creation, if CONFIG_FILE is set to a non default location.
  README.md
  installer/main.wxs
Labels: 🐞 bug

#2165 collector: Add disable flag
  cmd/windows_exporter/main.go
  pkg/collector/collection.go
Labels: ✨ enhancement

#2185 chore: update to go 1.25
  go.mod
Labels: ✨ enhancement

#2188 mi: remove callbacks
  .idea/dictionaries/project.xml
  internal/mi/callbacks.go
  internal/mi/mi_test.go
  internal/mi/operation.go
  internal/mi/session.go
  internal/utils/testutils/handle.go
Labels: ✨ enhancement

#2186 gpu: add device id label
  .idea/dictionaries/project.xml
  docs/collector.gpu.md
  internal/collector/gpu/gpu.go
  internal/collector/gpu/utils.go
  internal/headers/cfgmgr32/cfgmgr32.go
  internal/headers/cfgmgr32/syscall.go
  internal/headers/cfgmgr32/types.go
  internal/headers/gdi32/gdi32.go
  internal/headers/gdi32/types.go
  internal/headers/win32/types.go
  internal/headers/win32/utils.go
Labels: 🐞 bug, 🐞 bug/backport

#2191 installer: set failureflag for Windows service
  .gitignore
  installer/main.wxs
Labels: ✨ enhancement

#2192 docs: Fixed HTTP request metrics documentation
  docs/collector.iis.md
Labels: 📖 docs
