Repository prometheus-community/windows_exporter, pull requests merged in 2025-06, with the labels that each got.

#2070 gpu: add info metric about devices
  .idea/dictionaries/project.xml
  docs/collector.gpu.md
  internal/collector/gpu/gpu.go
  internal/headers/setupapi/gpu.go
  internal/headers/setupapi/gpu_test.go
  internal/headers/setupapi/setupapi.go
  internal/headers/setupapi/types.go
Labels: chore

#2073 docs: fix typo in dns docs subcollector name
  docs/collector.dns.md
Labels: 📖 docs

#1948 iis: Add HTTP Service Request Queues
  docs/collector.iis.md
  internal/collector/iis/iis.go
  internal/collector/iis/iis_http_service_request_queues.go
Labels: ✨ enhancement

#2080 config: fix validation error with empty config files
  internal/config/config.go
Labels: 🐞 bug

#2084 logical_disk: skip unmounted volumes
  internal/collector/logical_disk/logical_disk.go
Labels: 🐞 bug

#2087 docs: Clearify Windows Server 2012R2 support
  README.md
Labels: 📖 docs

#2090 [0.30] logical_disk: skip unmounted volumes (#2084)
  internal/collector/logical_disk/logical_disk.go
Labels: 🐞 bug

#2092 [0.30] service: report invalid parameter errors as debug (#2051)
  internal/collector/service/service.go
Labels: 🐞 bug

#2093 docs: add note about Server 2012
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: 📖 docs

#2099 Update collector.mscluster.md
  docs/collector.mscluster.md
Labels: 📖 docs
